# Integrate fetal ovary snRNA-seq with the selected adult ovary CELLxGENE reference.
#
# Integration uses:
#   - fetal RNA/data generated by LogNormalize
#   - adult RNA/data from CELLxGENE adata$X, already normalized/log-like
#   - gene-symbol intersection
#   - RPCA anchors
#   - Seurat IntegrateData
#
# RNA/counts layers are preserved for downstream pseudobulk analyses.

suppressPackageStartupMessages({
  library(Seurat)
  library(SeuratObject)
  library(Matrix)
  library(dplyr)
  library(readr)
  library(tibble)
})

set.seed(42)
options(bitmapType = "cairo")

project_root <- "/home/liyan/liyan/Final/github_code_for_publication"
results_base <- "/home/liyan/liyan/Final/github_code_for_publication_results"

source(file.path(project_root, "config", "labels_colors.R"))

paths_local <- file.path(project_root, "config", "paths_local.R")
if (file.exists(paths_local)) {
  source(paths_local)
}

default_fetal_rds <- file.path(
  results_base,
  "snRNAseq_annotated_object",
  "objects",
  "fetal_ovary_snRNAseq_canonical_annotated.rds"
)

default_adult_rds <- file.path(
  results_base,
  "adult_cellxgene_reference",
  "objects",
  "adult_cellxgene_584027d5_seurat.rds"
)
fetal_rds <- if (exists("fetal_annotated_rds", inherits = FALSE)) {
  fetal_annotated_rds
} else {
  default_fetal_rds
}

adult_rds <- if (exists("adult_cellxgene_seurat_rds", inherits = FALSE)) {
  adult_cellxgene_seurat_rds
} else {
  default_adult_rds
}

integration_results_root <- file.path(results_base, "fetal_adult_integration")

out_object_dir <- file.path(integration_results_root, "objects")
out_table_dir <- file.path(integration_results_root, "tables")
out_log_dir <- file.path(integration_results_root, "logs")

dir.create(out_object_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(out_table_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(out_log_dir, recursive = TRUE, showWarnings = FALSE)

out_rds <- file.path(
  out_object_dir,
  "fetal_adult_integrated_snRNAseq.rds"
)

integration_nfeatures <- 3000
pca_dimensions <- 50
anchor_dimensions <- 1:30

get_layers_safe <- function(object, assay = "RNA") {
  as.character(
    tryCatch(
      Layers(object[[assay]]),
      error = function(e) character(0)
    )
  )
}

get_layer_matrix <- function(object, assay = "RNA", layer) {
  matrix <- LayerData(object, assay = assay, layer = layer)

  if (!inherits(matrix, "dgCMatrix")) {
    matrix <- as(matrix, "dgCMatrix")
  }

  matrix
}

ensure_data_layer <- function(object, assay = "RNA") {
  layers_present <- get_layers_safe(object, assay = assay)

  if ("data" %in% layers_present) {
    return(object)
  }

  data_candidates <- layers_present[grepl("^data($|\\.)", layers_present)]

  if (length(data_candidates) > 0) {
    source_layer <- data_candidates[[1]]
    message("Creating ", assay, "/data from ", source_layer)

    source_matrix <- LayerData(object, assay = assay, layer = source_layer)

    object <- SetAssayData(
      object,
      assay = assay,
      layer = "data",
      new.data = source_matrix
    )
    return(object)
  }

  count_candidates <- layers_present[grepl("^counts($|\\.)", layers_present)]

  if (length(count_candidates) > 0) {
    source_layer <- count_candidates[[1]]
    message("Creating ", assay, "/data from ", source_layer)

    source_matrix <- LayerData(object, assay = assay, layer = source_layer)

    object <- SetAssayData(
      object,
      assay = assay,
      layer = "data",
      new.data = source_matrix
    )

    return(object)
  }

  stop(
    "No data-like or counts-like layer was found in assay ",
    assay,
    ". Available layers: ",
    paste(layers_present, collapse = ", ")
  )
}

check_counts_layer <- function(object, layer, assay = "RNA", label) {
  matrix <- get_layer_matrix(object, assay = assay, layer = layer)

  fraction_noninteger <- if (length(matrix@x) > 0) {
    mean(abs(matrix@x - round(matrix@x)) > 1e-6)
  } else {
    0
  }

  value_range <- if (length(matrix@x) > 0) {
    range(matrix@x)
  } else {
    c(0, 0)
  }

  tibble(
    dataset = label,
    assay = assay,
    layer = layer,
    genes = nrow(matrix),
    cells = ncol(matrix),
    nonzero_values = length(matrix@x),
    fraction_noninteger = fraction_noninteger,
    min_value = value_range[[1]],
    max_value = value_range[[2]]
  )
}

canonicalize_label <- function(x) {
  x <- as.character(x)
  x <- tolower(x)
  x <- gsub("_", " ", x)
  x <- gsub("\\s+", " ", x)
  trimws(x)
}
harmonize_adult_cell_type <- function(cell_type) {
  original <- as.character(cell_type)
  canonical <- canonicalize_label(original)

  mapping <- c(
    "b cell" = "immune",
    "classical monocyte" = "immune",
    "monocyte" = "immune",
    "immune cell" = "immune",
    "leukocyte" = "immune",
    "macrophage" = "immune",
    "mast cell" = "immune",
    "mature nk t cell" = "immune",
    "myeloid dendritic cell" = "immune",
    "neutrophil" = "immune",
    "plasma cell" = "immune",
    "plasmacytoid dendritic cell" = "immune",
    "t cell" = "immune",
    "cd4-positive, alpha-beta t cell" = "immune",
    "cd8-positive, alpha-beta t cell" = "immune",
    "hematopoietic precursor cell" = "immune",

    "oocyte" = "germ",

    "epithelial cell" = "epithelial",
    "ovarian surface epithelial cell" = "epithelial",
    "glandular secretory epithelial cell" = "epithelial",

    "stromal cell" = "stroma",
    "stromal cell of ovary" = "stroma",

    "theca cell" = "theca",
    "theca stroma" = "theca",

    "blood vessel smooth muscle cell" = "mural",
    "smooth muscle pericyte" = "mural",
    "pericyte" = "mural",

    "endothelial cell" = "endothelial",

    "glial cell" = "glial",
    "unknown" = "unknown"
  )

  harmonized <- original
  hit <- canonical %in% names(mapping)

  harmonized[hit] <- unname(mapping[canonical[hit]])

  # Keep this adult population separate from mural, matching the established
  # project decision.
  harmonized[canonical == "smooth muscle cell"] <- "smooth muscle cell"

  harmonized
}

write_count_table <- function(metadata, column, file) {
  if (!column %in% colnames(metadata)) {
    return(invisible(NULL))
  }

  out <- metadata |>
    count(.data[[column]], name = "n_cells") |>
    arrange(desc(n_cells))

  colnames(out)[1] <- column

  write_csv(out, file)

  invisible(NULL)
}
compute_rna_layer_coverage <- function(object) {
  layers <- get_layers_safe(object, assay = "RNA")
  datasets <- sort(unique(as.character(object$dataset)))

  rows <- list()

  for (layer in layers) {
    layer_cells <- colnames(get_layer_matrix(object, assay = "RNA", layer = layer))

    for (dataset in datasets) {
      dataset_cells <- colnames(object)[as.character(object$dataset) == dataset]

      rows[[length(rows) + 1]] <- tibble(
        layer = layer,
        dataset = dataset,
        cells_in_dataset = length(dataset_cells),
        cells_in_layer = length(intersect(dataset_cells, layer_cells)),
        fraction_covered = ifelse(
          length(dataset_cells) > 0,
          length(intersect(dataset_cells, layer_cells)) / length(dataset_cells),
          NA_real_
        )
      )
    }
  }

  bind_rows(rows)
}

message("Loading fetal object:\n  ", fetal_rds)
stopifnot(file.exists(fetal_rds))
fetal <- readRDS(fetal_rds)

message("Loading adult object:\n  ", adult_rds)
stopifnot(file.exists(adult_rds))
adult <- readRDS(adult_rds)

stopifnot(inherits(fetal, "Seurat"))
stopifnot(inherits(adult, "Seurat"))

DefaultAssay(fetal) <- "RNA"
DefaultAssay(adult) <- "RNA"

required_fetal_cols <- c(
  "major_cell_type",
  "fine_subcluster",
  "final_annotation",
  "annotation_version",
  "annotation_source"
)

missing_fetal_cols <- setdiff(required_fetal_cols, colnames(fetal@meta.data))

if (length(missing_fetal_cols) > 0) {
  stop("Fetal object is missing required metadata: ", paste(missing_fetal_cols, collapse = ", "))
}
if (!"sampleID" %in% colnames(fetal@meta.data)) {
  if ("sample_id" %in% colnames(fetal@meta.data)) {
    fetal$sampleID <- as.character(fetal$sample_id)
  } else {
    stop("Fetal object is missing sampleID/sample_id metadata.")
  }
}

if (!"cell_type" %in% colnames(adult@meta.data)) {
  stop("Adult object is missing expected CELLxGENE cell_type metadata.")
}

if (!"donor_id" %in% colnames(adult@meta.data)) {
  stop("Adult object is missing expected donor_id metadata.")
}

fetal_layers <- get_layers_safe(fetal, assay = "RNA")
adult_layers <- get_layers_safe(adult, assay = "RNA")

if (!"counts" %in% adult_layers) {
  stop("Adult RNA assay must contain a counts layer for downstream pseudobulk.")
}

if (!"data" %in% adult_layers) {
  stop("Adult RNA assay must contain a data layer for integration.")
}

adult_matrix_qc <- bind_rows(
  check_counts_layer(adult, layer = "counts", assay = "RNA", label = "adult_counts"),
  check_counts_layer(adult, layer = "data", assay = "RNA", label = "adult_data")
)

write_csv(
  adult_matrix_qc,
  file.path(out_table_dir, "adult_reference_matrix_qc_before_integration.csv")
)

adult_counts_fraction_noninteger <- adult_matrix_qc$fraction_noninteger[
  adult_matrix_qc$dataset == "adult_counts"
]

adult_data_fraction_noninteger <- adult_matrix_qc$fraction_noninteger[
  adult_matrix_qc$dataset == "adult_data"
]

if (adult_counts_fraction_noninteger > 0.001) {
  stop("Adult RNA/counts is not count-like. Rerun adult reference preparation.")
}

if (adult_data_fraction_noninteger < 0.001) {
  warning("Adult RNA/data appears integer-like, but expected normalized/log-like data.")
}
fetal$dataset <- "fetal"
adult$dataset <- "adult"

fetal$developmental_stage <- "fetal"
adult$developmental_stage <- "adult"

# Compatibility with existing downstream scripts:
# fetal cell_type is the final major cell type;
# adult cell_type remains the original CELLxGENE label.
fetal$cell_type <- as.character(fetal$major_cell_type)
adult$adult_cell_type_original <- as.character(adult$cell_type)
adult$adult_cell_type_harmonized <- harmonize_adult_cell_type(adult$adult_cell_type_original)

fetal$fetal_major_cell_type <- as.character(fetal$major_cell_type)
fetal$fetal_fine_subcluster <- as.character(fetal$fine_subcluster)
fetal$fetal_final_annotation <- as.character(fetal$final_annotation)

adult$major_cell_type <- NA_character_
adult$fine_subcluster <- NA_character_
adult$final_annotation <- NA_character_
adult$annotation_version <- NA_character_
adult$annotation_source <- NA_character_
adult$fetal_major_cell_type <- NA_character_
adult$fetal_fine_subcluster <- NA_character_
adult$fetal_final_annotation <- NA_character_

fetal$adult_cell_type_original <- NA_character_
fetal$adult_cell_type_harmonized <- NA_character_

if (!"sampleID" %in% colnames(adult@meta.data)) {
  adult$sampleID <- NA_character_
}

if (!"donor_id" %in% colnames(fetal@meta.data)) {
  fetal$donor_id <- NA_character_
}

fetal <- ensure_data_layer(fetal, assay = "RNA")
adult <- ensure_data_layer(adult, assay = "RNA")

message("Fetal dimensions: ", nrow(fetal), " genes x ", ncol(fetal), " cells")
message("Adult dimensions: ", nrow(adult), " genes x ", ncol(adult), " cells")

common_features <- intersect(rownames(fetal), rownames(adult))

message("Common features: ", length(common_features))

if (length(common_features) <= 2000) {
  stop("Too few common features for integration: ", length(common_features))
}

write_csv(
  tibble(feature = common_features),
  file.path(out_table_dir, "fetal_adult_common_features.csv")
)

fetal_int <- subset(fetal, features = common_features)
adult_int <- subset(adult, features = common_features)

DefaultAssay(fetal_int) <- "RNA"
DefaultAssay(adult_int) <- "RNA"
message("Normalizing fetal data.")
fetal_int <- NormalizeData(
  fetal_int,
  normalization.method = "LogNormalize",
  scale.factor = 1e4,
  verbose = FALSE
)

fetal_int <- FindVariableFeatures(
  fetal_int,
  selection.method = "vst",
  nfeatures = integration_nfeatures,
  verbose = FALSE
)

message("Using adult RNA/data as normalized/log-like expression; not running NormalizeData on adult.")

adult_int <- ensure_data_layer(adult_int, assay = "RNA")

adult_int <- FindVariableFeatures(
  adult_int,
  selection.method = "mvp",
  nfeatures = integration_nfeatures,
  verbose = FALSE
)

features_use <- union(
  VariableFeatures(fetal_int),
  VariableFeatures(adult_int)
)

features_use <- intersect(features_use, common_features)

message("Integration features: ", length(features_use))

if (length(features_use) <= 500) {
  stop("Too few integration features: ", length(features_use))
}

write_csv(
  tibble(feature = features_use),
  file.path(out_table_dir, "fetal_adult_integration_features.csv")
)

message("Scaling and running PCA for fetal dataset.")
fetal_int <- ScaleData(
  fetal_int,
  features = features_use,
  verbose = FALSE
)

fetal_int <- RunPCA(
  fetal_int,
  features = features_use,
  npcs = pca_dimensions,
  verbose = FALSE
)

message("Scaling and running PCA for adult dataset.")
adult_int <- ScaleData(
  adult_int,
  features = features_use,
  verbose = FALSE
)
adult_int <- RunPCA(
  adult_int,
  features = features_use,
  npcs = pca_dimensions,
  verbose = FALSE
)

message("Finding RPCA integration anchors.")
anchors <- FindIntegrationAnchors(
  object.list = list(fetal_int, adult_int),
  anchor.features = features_use,
  reduction = "rpca",
  dims = anchor_dimensions
)

message("Integrating data.")
integrated <- IntegrateData(
  anchorset = anchors,
  dims = anchor_dimensions
)

DefaultAssay(integrated) <- "integrated"

integrated_layers <- get_layers_safe(integrated, assay = "integrated")

if (!"data" %in% integrated_layers) {
  stop("Integrated assay does not contain a data layer.")
}

message("Running integrated PCA and UMAP.")
integrated <- ScaleData(
  integrated,
  verbose = FALSE
)

integrated <- RunPCA(
  integrated,
  npcs = pca_dimensions,
  verbose = FALSE
)

integrated <- RunUMAP(
  integrated,
  reduction = "pca",
  dims = anchor_dimensions,
  verbose = FALSE
)

is_fetal <- as.character(integrated$dataset) == "fetal"
is_adult <- as.character(integrated$dataset) == "adult"

integrated$cell_type_joint <- NA_character_
integrated$cell_type_joint[is_fetal] <- as.character(integrated$cell_type[is_fetal])
integrated$cell_type_joint[is_adult] <- as.character(integrated$adult_cell_type_harmonized[is_adult])

integrated$celltype_prefixed <- paste0(
  as.character(integrated$dataset),
  ": ",
  integrated$cell_type_joint
)
if (anyNA(integrated$cell_type_joint)) {
  stop("cell_type_joint contains missing values after harmonization.")
}

expected_cells <- ncol(fetal) + ncol(adult)

stopifnot(
  ncol(integrated) == expected_cells,
  all(c("pca", "umap") %in% names(integrated@reductions)),
  "RNA" %in% names(integrated@assays),
  "integrated" %in% names(integrated@assays),
  "cell_type" %in% colnames(integrated@meta.data),
  "adult_cell_type_harmonized" %in% colnames(integrated@meta.data),
  "cell_type_joint" %in% colnames(integrated@meta.data),
  "celltype_prefixed" %in% colnames(integrated@meta.data),
  "sampleID" %in% colnames(integrated@meta.data),
  "donor_id" %in% colnames(integrated@meta.data)
)

rna_layer_coverage <- compute_rna_layer_coverage(integrated)

write_csv(
  rna_layer_coverage,
  file.path(out_table_dir, "fetal_adult_integrated_rna_layer_coverage.csv")
)

write_csv(
  integrated@meta.data |>
    count(dataset, name = "n_cells") |>
    arrange(dataset),
  file.path(out_table_dir, "fetal_adult_dataset_counts.csv")
)

write_count_table(
  integrated@meta.data[is_fetal, , drop = FALSE],
  "cell_type",
  file.path(out_table_dir, "fetal_cell_type_counts.csv")
)

write_count_table(
  integrated@meta.data[is_fetal, , drop = FALSE],
  "final_annotation",
  file.path(out_table_dir, "fetal_final_annotation_counts.csv")
)

write_count_table(
  integrated@meta.data[is_adult, , drop = FALSE],
  "adult_cell_type_original",
  file.path(out_table_dir, "adult_cell_type_original_counts.csv")
)

write_count_table(
  integrated@meta.data[is_adult, , drop = FALSE],
  "adult_cell_type_harmonized",
  file.path(out_table_dir, "adult_cell_type_harmonized_counts.csv")
)

write_count_table(
  integrated@meta.data,
  "celltype_prefixed",
  file.path(out_table_dir, "fetal_adult_prefixed_cell_type_counts.csv")
)

saveRDS(integrated, out_rds)
summary_lines <- c(
  paste("Input fetal object:", fetal_rds),
  paste("Input adult object:", adult_rds),
  paste("Output integrated object:", out_rds),
  paste("Fetal cells:", ncol(fetal)),
  paste("Adult cells:", ncol(adult)),
  paste("Integrated cells:", ncol(integrated)),
  paste("Integrated genes:", nrow(integrated)),
  paste("Common features:", length(common_features)),
  paste("Integration features:", length(features_use)),
  paste("Integration nfeatures:", integration_nfeatures),
  paste("PCA dimensions:", pca_dimensions),
  paste("Anchor dimensions:", paste(range(anchor_dimensions), collapse = "-")),
  paste("Integrated assay layers:", paste(integrated_layers, collapse = ", ")),
  paste("RNA assay layers:", paste(get_layers_safe(integrated, assay = "RNA"), collapse = ", ")),
  paste("Adult RNA/counts fraction non-integer before integration:", signif(adult_counts_fraction_noninteger, 4)),
  paste("Adult RNA/data fraction non-integer before integration:", signif(adult_data_fraction_noninteger, 4)),
  paste("Datasets:", paste(names(table(integrated$dataset)), table(integrated$dataset), collapse = "; ")),
  paste("Fetal cell types:", paste(sort(unique(integrated$cell_type[is_fetal])), collapse = ", ")),
  paste("Adult harmonized cell types:", paste(sort(unique(integrated$adult_cell_type_harmonized[is_adult])), collapse = ", ")),
  paste("Output directory:", integration_results_root),
  paste("Output object size GB:", round(file.info(out_rds)$size / 1024^3, 2))
)

writeLines(summary_lines, file.path(out_log_dir, "fetal_adult_integration_summary.txt"))

sink(file.path(out_log_dir, "fetal_adult_integration_sessionInfo.txt"))
print(sessionInfo())
sink()

cat("\nDataset counts:\n")
print(table(integrated$dataset, useNA = "ifany"))

cat("\nFetal cell types:\n")
print(sort(table(integrated$cell_type[is_fetal], useNA = "ifany"), decreasing = TRUE))

cat("\nAdult harmonized cell types:\n")
print(sort(table(integrated$adult_cell_type_harmonized[is_adult], useNA = "ifany"), decreasing = TRUE))

cat("\nRNA layer coverage:\n")
print(rna_layer_coverage)

cat("\nSaved fetal-adult integrated object:\n  ", out_rds, "\n", sep = "")
cat("File size: ", round(file.info(out_rds)$size / 1024^3, 2), " GB\n", sep = "")
